name = "SimpleAndCleanBlog"
license = "MIT"
licenselink = ""
description = "A theme for hugo websites."
homepage = "https://github.com/hodanov/simple-and-clean-blog"
tags = ["Website", "Blog", "Hugo"]
features = []
min_version = "0.0.1"

[author]
  name = "hodanov"
  homepage = "https://github.com/hodanov"
